#!/bin/bash
echo "compiling maryo..."
echo "target: windows i386.."
env GOOS=windows GOARCH=386 go build -o "maryo-windows-i386.exe"
echo "target: windows amd64.."
env GOOS=windows GOARCH=amd64 go build -o "maryo-windows-amd64.exe"
echo "target: linux arm.."
env GOOS=linux GOARCH=arm go build -o "maryo-linux-arm"
echo "target: linux arm64.."
env GOOS=linux GOARCH=arm64 go build -o "maryo-linux-arm64"
echo "target: linux i386.."
env GOOS=linux GOARCH=386 go build -o "maryo-linux-i386"
echo "target: linux amd64.."
env GOOS=linux GOARCH=amd64 go build -o "maryo-linux-amd64"
echo "target: darwin i386.."
env GOOS=darwin GOARCH=386 go build -o "maryo-darwin-i386"
echo "target: darwin amd64.."
env GOOS=darwin GOARCH=amd64 go build -o "maryo-darwin-amd64"
echo "finished compiling maryo for 3 OSes across 4 different architectures..."
